name: Hello world
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: BUILD  steps
        run: |
         echo "first line of build"
         echo "second line of build"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test steps
        run: |
         echo "first line of test"
         echo "second line of test"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy steps
        run: |
         echo "first line of deploy"
         echo "second line of deploy"
